version: "3"
services:
  paddleocr:
    image: c403/paddleocr:2.2.2
    network_mode: bridge
    container_name: paddleocr
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 5000:5000